Repository ProtectMong/sonmong-backend, pull requests merged in 2024-03, with the labels that each got.

#3 [FEAT] 파일구조세팅
  .gitignore
  src/main/java/poten012/sonmong/Poten403/common/ApiResponse.java
  src/main/java/poten012/sonmong/Poten403/common/ErrorHandler.java
  src/main/java/poten012/sonmong/Poten403/common/entity/superclass/TimeStamped.java
  src/main/java/poten012/sonmong/Poten403/common/exception/Exception.java
  src/main/java/poten012/sonmong/Poten403/common/message/Message.java
  src/main/java/poten012/sonmong/Poten403/common/util/Util.java
  src/main/java/poten012/sonmong/Poten403/config/chatgpt/GptConfig.java
  src/main/java/poten012/sonmong/Poten403/config/jwt/JwtConfig.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/controller.java
  src/main/java/poten012/sonmong/Poten403/domain/social/controller.java
  src/main/java/poten012/sonmong/Poten403/domain/user/controller.java
Labels: juyoung, S

#4 [FEAT] chatGPT api 연동
  build.gradle
  src/main/java/poten012/sonmong/Poten403/common/message/ExceptionMessage.java
  src/main/java/poten012/sonmong/Poten403/common/message/ResponseMessage.java
  src/main/java/poten012/sonmong/Poten403/config/chatgpt/ChatGPTConfig.java
  src/main/java/poten012/sonmong/Poten403/config/chatgpt/GptConfig.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/controller.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/domain/Message.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/dto/ChatRequestDto.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/dto/ChatResponseDto.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/presentation/Controller.java
  src/main/resources/application.yml
Labels: juyoung, M, feat

#9 [Feat] ncp 인프라 구축
  .github/workflows/cd-develop.yml
  .github/workflows/ci-backend.yml
  .gitignore
  Dockerfile
  Makefile
  app_setup.sh
  build.gradle
  docker-compose.yml
  src/main/resources/application.yml
Labels: daeho, feat

#7 [FEAT] Curation 기능 개발
  build.gradle
  src/main/java/poten012/sonmong/Poten403/Poten403Application.java
  src/main/java/poten012/sonmong/Poten403/common/entity/superclass/TimeStamped.java
  src/main/java/poten012/sonmong/Poten403/common/message/ExceptionMessage.java
  src/main/java/poten012/sonmong/Poten403/common/message/ResponseMessage.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/domain/Curation.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/domain/CurationAnswer.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/request/CurationRequestDto.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/response/AiConsultingMainResponseDto.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/response/CurationDetailResponseDto.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/response/CurationResponseDto.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/response/CurationResponseVo.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/facade/AiConsultingFacade.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/presentation/AiConsultingController.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/repository/CurationAnswerRepository.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/repository/CurationRepository.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/service/AiConsultingService.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/service/AiConsultingServiceImpl.java
  src/main/java/poten012/sonmong/Poten403/domain/chatgpt/service/ChatGPTService.java
  src/main/java/poten012/sonmong/Poten403/domain/user/UserController.java
  src/main/java/poten012/sonmong/Poten403/domain/user/controller.java
  src/main/java/poten012/sonmong/Poten403/domain/user/domain/User.java
  src/main/java/poten012/sonmong/Poten403/domain/user/repository/UserRepository.java
Labels: juyoung, M, feat

#13 [FIX] curation 응답 수정
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/dto/response/CurationResponseDto.java
  src/main/java/poten012/sonmong/Poten403/domain/aiconsulting/service/AiConsultingServiceImpl.java
Labels: juyoung, S, fix
